apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationName }}-web-server-service
  labels:
    app.kubernetes.io/name: web-server
    app.kubernetes.io/component: load-balancer
{{ include "recommended-labels" . | indent 4 }}
{{ include "ingress-label" . | indent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: traffic-port
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /
spec:
  type: LoadBalancer
  selector:
{{ include "ingress-label" . | indent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    - name: https
      protocol: TCP
      port: 443
      targetPort: https